// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcoH3QzkT1rjp5B6rRLFapinAhA__4pAE',
    appId: '1:471185690405:web:69d2a096be17e2e26b14cc',
    messagingSenderId: '471185690405',
    projectId: 'walk-and-discover-73c11',
    authDomain: 'walk-and-discover-73c11.firebaseapp.com',
    storageBucket: 'walk-and-discover-73c11.firebasestorage.app',
    measurementId: 'G-RNSY4YMM87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbOtGFZjVPtXYnCsh0iMP8z3DWEOdxm8o',
    appId: '1:471185690405:android:05e5625515d0cf286b14cc',
    messagingSenderId: '471185690405',
    projectId: 'walk-and-discover-73c11',
    storageBucket: 'walk-and-discover-73c11.firebasestorage.app',
  );
}
